server:
  port: 8080 # Gateway service port

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:${VITE_AUTH_SERVICE_PORT} 
          predicates:
            - Path=/api/v1/auth/**

        - id: event-service
          uri: http://localhost:${VITE_EVENT_SERVICE_PORT} 
          predicates:
            - Path=/api/v1/events/**

        - id: payment-service
          uri: http://localhost:${VITE_PAYMENT_SERVICE_PORT}
          predicates:
            - Path=/api/payment/**

        - id: notification-service
          uri: http://localhost:${VITE_NOTIFICATION_SERVICE_PORT}
          predicates:
            - Path=/notify/**
